// src/login/pages/Info.tsx
import type { PageProps } from "keycloakify/login/pages/PageProps";
import { kcSanitize } from "keycloakify/lib/kcSanitize";
import type { KcContext } from "../KcContext";
import type { I18n } from "../i18n";

export default function Info(props: PageProps<Extract<KcContext, { pageId: "info.ftl" }>, I18n>) {
  const { kcContext, i18n, doUseDefaultCss, Template, classes } = props;

  const { advancedMsgStr, msg } = i18n;

  const { messageHeader, message, requiredActions, skipLink, pageRedirectUri, actionUri, client } = kcContext;

  return (
    <Template
      kcContext={kcContext}
      i18n={i18n}
      doUseDefaultCss={doUseDefaultCss}
      classes={classes}
      displayMessage={false}
      headerNode={
        <span
          dangerouslySetInnerHTML={{
            __html: kcSanitize(messageHeader ?? message.summary)
          }}
        />
      }
    >
      <div id="kc-info-message">
        <p
          className="instruction"
          dangerouslySetInnerHTML={{
            __html: kcSanitize(
              (() => {
                let html = message.summary?.trim();

                if (requiredActions) {
                  html += " <b>";

                  html += requiredActions.map(requiredAction => advancedMsgStr(`requiredAction.${requiredAction}`)).join(", ");

                  html += "</b>";
                }

                return html;
              })()
            )
          }}
        />
        {(() => {
          if (skipLink) {
            return null;
          }

          if (pageRedirectUri) {
            return (
              <p>
                <a href={pageRedirectUri}>{msg("backToApplication")}</a>
              </p>
            );
          }
          if (actionUri) {
            return (
              <p>
                <a href={actionUri}>{msg("proceedWithAction")}</a>
              </p>
            );
          }

          if (client.baseUrl) {
            return (
              <p>
                <a href={client.baseUrl}>{msg("backToApplication")}</a>
              </p>
            );
          }
        })()}
      </div>
    </Template>
  );
}

// src/login/pages/Info.svelte
<script lang="ts">
  import type { PageProps } from "@keycloakify/svelte/login/pages/PageProps";
  import { kcSanitize } from "keycloakify/lib/kcSanitize";
  import type { KcContext } from "../KcContext";
  import type { I18n } from "../i18n";

  const {
    Template,
    kcContext,
    i18n,
    doUseDefaultCss,
    classes,
  }: PageProps<Extract<KcContext, { pageId: "info.ftl" }>, I18n> = $props();

  const { advancedMsgStr, msg } = $i18n;

  const {
    messageHeader,
    message,
    requiredActions,
    skipLink,
    pageRedirectUri,
    actionUri,
    client,
  } = kcContext;
</script>

<Template {kcContext} {i18n} {doUseDefaultCss} {classes} displayMessage={false}>
  {#snippet headerNode()}
    <span>{@html kcSanitize(messageHeader ?? message.summary)}</span>
  {/snippet}

  <div id="kc-info-message">
    <p class="instruction">
      {@html kcSanitize(
        (() => {
          let html = message.summary;

          if (requiredActions) {
            html += "<b>";

            html += requiredActions
              .map((requiredAction) =>
                advancedMsgStr(`requiredAction.${requiredAction}`),
              )
              .join(", ");

            html += "</b>";
          }

          return html;
        })(),
      )}
    </p>
    {#if !skipLink}
      {#if pageRedirectUri}
        <p>
          <a href={pageRedirectUri}>{@render msg("backToApplication")()}</a>
        </p>
      {:else if actionUri}
        <p>
          <a href={actionUri}>{@render msg("proceedWithAction")()}</a>
        </p>
      {:else if client.baseUrl}<p>
          <a href={client.baseUrl}>{@render msg("backToApplication")()}</a>
        </p>
      {/if}
    {/if}
  </div>
</Template>
