// src/login/pages/LoginUsername.svelte
<script lang="ts">
  import type { PageProps } from "@keycloakify/svelte/login/pages/PageProps";
  import { useState } from "@keycloakify/svelte/tools/useState";
  import { getKcClsx } from "keycloakify/login/lib/kcClsx";
  import { clsx } from "keycloakify/tools/clsx";
  import type { KcContext } from "../KcContext";
  import type { I18n } from "../i18n";

  const {
    Template,
    kcContext,
    i18n,
    doUseDefaultCss,
    classes,
  }: PageProps<
    Extract<KcContext, { pageId: "login-username.ftl" }>,
    I18n
  > = $props();

  const { kcClsx } = getKcClsx({
    doUseDefaultCss,
    classes,
  });

  const {
    social,
    realm,
    url,
    usernameHidden,
    login,
    registrationDisabled,
    messagesPerField,
  } = kcContext;

  const { msg, msgStr } = $i18n;

  const [isLoginButtonDisabled, setIsLoginButtonDisabled] = useState(false);
</script>

<Template
  {kcContext}
  {i18n}
  {doUseDefaultCss}
  {classes}
  displayMessage={!messagesPerField.existsError("username")}
  displayInfo={realm.password &&
    realm.registrationAllowed &&
    !registrationDisabled}
>
  {#snippet headerNode()}
    {@render msg("doLogIn")()}
  {/snippet}
  {#snippet infoNode()}
    <div id="kc-registration">
      <span>
        {@render msg("noAccount")()}
        <a tabindex={6} href={url.registrationUrl}>
          {@render msg("doRegister")()}
        </a>
      </span>
    </div>
  {/snippet}
  {#snippet socialProvidersNode()}
    {#if realm.password && social?.providers !== undefined && social.providers.length !== 0}
      <div
        id="kc-social-providers"
        class={kcClsx("kcFormSocialAccountSectionClass")}
      >
        <hr />
        <h2>{@render msg("identity-provider-login-label")()}</h2>
        <ul
          class={kcClsx(
            "kcFormSocialAccountListClass",
            social.providers.length > 3 && "kcFormSocialAccountListGridClass",
          )}
        >
          {#each social.providers as p}
            <li>
              <a
                id={`social-${p.alias}`}
                class={kcClsx(
                  "kcFormSocialAccountListButtonClass",
                  social.providers.length > 3 && "kcFormSocialAccountGridItem",
                )}
                type="button"
                href={p.loginUrl}
              >
                {#if p.iconClasses}
                  <i
                    class={clsx(kcClsx("kcCommonLogoIdP"), p.iconClasses)}
                    aria-hidden="true"
                  ></i>
                {/if}
                <span
                  class={clsx(
                    kcClsx("kcFormSocialAccountNameClass"),
                    p.iconClasses && "kc-social-icon-text",
                  )}
                >
                  {p.displayName}
                </span>
              </a>
            </li>
          {/each}
        </ul>
      </div>
    {/if}
  {/snippet}

  <div id="kc-form">
    <div id="kc-form-wrapper">
      {#if realm.password}
        <form
          id="kc-form-login"
          onsubmit={() => {
            setIsLoginButtonDisabled(true);
            return true;
          }}
          action={url.loginAction}
          method="post"
        >
          {#if !usernameHidden}
            <div class={kcClsx("kcFormGroupClass")}>
              <label for="username" class={kcClsx("kcLabelClass")}>
                {#if !realm.loginWithEmailAllowed}
                  {@render msg("username")()}
                {:else if !realm.registrationEmailAsUsername}
                  {@render msg("usernameOrEmail")()}
                {:else}
                  {@render msg("email")()}
                {/if}
              </label>
              <!-- svelte-ignore a11y_autofocus -->
              <input
                tabindex={2}
                id="username"
                class={kcClsx("kcInputClass")}
                name="username"
                value={login.username ?? ""}
                type="text"
                autofocus
                autocomplete="off"
                aria-invalid={messagesPerField.existsError("username")}
              />
              {#if messagesPerField.existsError("username")}
                <span
                  id="input-error"
                  class={kcClsx("kcInputErrorMessageClass")}
                  aria-live="polite"
                >
                  {messagesPerField.getFirstError("username")}
                </span>
              {/if}
            </div>
          {/if}

          <div class={kcClsx("kcFormGroupClass", "kcFormSettingClass")}>
            <div id="kc-form-options">
              {#if realm.rememberMe && !usernameHidden}
                <div class="checkbox">
                  <label>
                    <input
                      tabindex={3}
                      id="rememberMe"
                      name="rememberMe"
                      type="checkbox"
                      checked={!!login.rememberMe}
                    />
                    {" "}
                    {@render msg("rememberMe")()}
                  </label>
                </div>
              {/if}
            </div>
          </div>

          <div id="kc-form-buttons" class={kcClsx("kcFormGroupClass")}>
            <input
              tabindex={4}
              disabled={$isLoginButtonDisabled}
              class={kcClsx(
                "kcButtonClass",
                "kcButtonPrimaryClass",
                "kcButtonBlockClass",
                "kcButtonLargeClass",
              )}
              name="login"
              id="kc-login"
              type="submit"
              value={msgStr("doLogIn")}
            />
          </div>
        </form>
      {/if}
    </div>
  </div>
</Template>

// src/login/pages/LoginUsername.tsx
import { useState } from "react";
import { clsx } from "keycloakify/tools/clsx";
import { getKcClsx } from "keycloakify/login/lib/kcClsx";
import type { PageProps } from "keycloakify/login/pages/PageProps";
import type { KcContext } from "../KcContext";
import type { I18n } from "../i18n";

export default function LoginUsername(props: PageProps<Extract<KcContext, { pageId: "login-username.ftl" }>, I18n>) {
  const { kcContext, i18n, doUseDefaultCss, Template, classes } = props;

  const { kcClsx } = getKcClsx({
    doUseDefaultCss,
    classes
  });

  const { social, realm, url, usernameHidden, login, registrationDisabled, messagesPerField } = kcContext;

  const { msg, msgStr } = i18n;

  const [isLoginButtonDisabled, setIsLoginButtonDisabled] = useState(false);

  return (
    <Template
      kcContext={kcContext}
      i18n={i18n}
      doUseDefaultCss={doUseDefaultCss}
      classes={classes}
      displayMessage={!messagesPerField.existsError("username")}
      displayInfo={realm.password && realm.registrationAllowed && !registrationDisabled}
      infoNode={
        <div id="kc-registration">
          <span>
            {msg("noAccount")}
            <a tabIndex={6} href={url.registrationUrl}>
              {msg("doRegister")}
            </a>
          </span>
        </div>
      }
      headerNode={msg("doLogIn")}
      socialProvidersNode={
        <>
          {realm.password && social?.providers !== undefined && social.providers.length !== 0 && (
            <div id="kc-social-providers" className={kcClsx("kcFormSocialAccountSectionClass")}>
              <hr />
              <h2>{msg("identity-provider-login-label")}</h2>
              <ul className={kcClsx("kcFormSocialAccountListClass", social.providers.length > 3 && "kcFormSocialAccountListGridClass")}>
                {social.providers.map((...[p, , providers]) => (
                  <li key={p.alias}>
                    <a
                      id={`social-${p.alias}`}
                      className={kcClsx("kcFormSocialAccountListButtonClass", providers.length > 3 && "kcFormSocialAccountGridItem")}
                      type="button"
                      href={p.loginUrl}
                    >
                      {p.iconClasses && <i className={clsx(kcClsx("kcCommonLogoIdP"), p.iconClasses)} aria-hidden="true"></i>}
                      <span className={clsx(kcClsx("kcFormSocialAccountNameClass"), p.iconClasses && "kc-social-icon-text")}>{p.displayName}</span>
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </>
      }
    >
      <div id="kc-form">
        <div id="kc-form-wrapper">
          {realm.password && (
            <form
              id="kc-form-login"
              onSubmit={() => {
                setIsLoginButtonDisabled(true);
                return true;
              }}
              action={url.loginAction}
              method="post"
            >
              {!usernameHidden && (
                <div className={kcClsx("kcFormGroupClass")}>
                  <label htmlFor="username" className={kcClsx("kcLabelClass")}>
                    {!realm.loginWithEmailAllowed ? msg("username") : !realm.registrationEmailAsUsername ? msg("usernameOrEmail") : msg("email")}
                  </label>
                  <input
                    tabIndex={2}
                    id="username"
                    className={kcClsx("kcInputClass")}
                    name="username"
                    defaultValue={login.username ?? ""}
                    type="text"
                    autoFocus
                    autoComplete="username"
                    aria-invalid={messagesPerField.existsError("username")}
                  />
                  {messagesPerField.existsError("username") && (
                    <span id="input-error" className={kcClsx("kcInputErrorMessageClass")} aria-live="polite">
                      {messagesPerField.getFirstError("username")}
                    </span>
                  )}
                </div>
              )}

              <div className={kcClsx("kcFormGroupClass", "kcFormSettingClass")}>
                <div id="kc-form-options">
                  {realm.rememberMe && !usernameHidden && (
                    <div className="checkbox">
                      <label>
                        <input tabIndex={3} id="rememberMe" name="rememberMe" type="checkbox" defaultChecked={!!login.rememberMe} />{" "}
                        {msg("rememberMe")}
                      </label>
                    </div>
                  )}
                </div>
              </div>

              <div id="kc-form-buttons" className={kcClsx("kcFormGroupClass")}>
                <input
                  tabIndex={4}
                  disabled={isLoginButtonDisabled}
                  className={kcClsx("kcButtonClass", "kcButtonPrimaryClass", "kcButtonBlockClass", "kcButtonLargeClass")}
                  name="login"
                  id="kc-login"
                  type="submit"
                  value={msgStr("doLogIn")}
                />
              </div>
            </form>
          )}
        </div>
      </div>
    </Template>
  );
}
