// src/login/pages/LoginPassword.svelte
<script lang="ts">
  import PasswordWrapper from "@keycloakify/svelte/login/components/PasswordWrapper.svelte";
  import type { PageProps } from "@keycloakify/svelte/login/pages/PageProps";
  import { useState } from "@keycloakify/svelte/tools/useState";
  import { kcSanitize } from "keycloakify/lib/kcSanitize";
  import { getKcClsx } from "keycloakify/login/lib/kcClsx";
  import { clsx } from "keycloakify/tools/clsx";
  import type { I18n } from "../i18n";
  import type { KcContext } from "../KcContext";

  const {
    Template,
    kcContext,
    i18n,
    doUseDefaultCss,
    classes,
  }: PageProps<
    Extract<KcContext, { pageId: "login-password.ftl" }>,
    I18n
  > = $props();

  const { kcClsx } = getKcClsx({
    doUseDefaultCss,
    classes,
  });

  const { realm, url, messagesPerField } = kcContext;

  const { msg, msgStr } = $i18n;

  const [isLoginButtonDisabled, setIsLoginButtonDisabled] = useState(false);
</script>

<Template
  {kcContext}
  {i18n}
  {doUseDefaultCss}
  {classes}
  displayMessage={!messagesPerField.existsError("password")}
>
  {#snippet headerNode()}
    {@render msg("doLogIn")()}
  {/snippet}

  <div id="kc-form">
    <div id="kc-form-wrapper">
      <form
        id="kc-form-login"
        onsubmit={() => {
          setIsLoginButtonDisabled(true);
          return true;
        }}
        action={url.loginAction}
        method="post"
      >
        <div class={clsx(kcClsx("kcFormGroupClass"), "no-bottom-margin")}>
          <label for="password" class={kcClsx("kcLabelClass")}>
            {@render msg("password")()}
          </label>

          <PasswordWrapper {kcClsx} {i18n} passwordInputId="password">
            <!-- svelte-ignore a11y_autofocus -->
            <input
              tabindex={2}
              id="password"
              class={kcClsx("kcInputClass")}
              name="password"
              type="password"
              autofocus
              autocomplete="on"
              aria-invalid={messagesPerField.existsError(
                "username",
                "password",
              )}
            />
          </PasswordWrapper>

          {#if messagesPerField.existsError("password")}
            <span
              id="input-error-password"
              class={kcClsx("kcInputErrorMessageClass")}
              aria-live="polite"
            >
              {@html kcSanitize(messagesPerField.get("password"))}
            </span>
          {/if}
        </div>
        <div class={kcClsx("kcFormGroupClass", "kcFormSettingClass")}>
          <div id="kc-form-options"></div>
          <div class={kcClsx("kcFormOptionsWrapperClass")}>
            {#if realm.resetPasswordAllowed}
              <span>
                <a tabindex={5} href={url.loginResetCredentialsUrl}>
                  {@render msg("doForgotPassword")()}
                </a>
              </span>
            {/if}
          </div>
        </div>
        <div id="kc-form-buttons" class={kcClsx("kcFormGroupClass")}>
          <input
            tabindex={4}
            class={kcClsx(
              "kcButtonClass",
              "kcButtonPrimaryClass",
              "kcButtonBlockClass",
              "kcButtonLargeClass",
            )}
            name="login"
            id="kc-login"
            type="submit"
            value={msgStr("doLogIn")}
            disabled={$isLoginButtonDisabled}
          />
        </div>
      </form>
    </div>
  </div>
</Template>

// src/login/pages/LoginPassword.tsx
import type { JSX } from "keycloakify/tools/JSX";
import { useState } from "react";
import { kcSanitize } from "keycloakify/lib/kcSanitize";
import { clsx } from "keycloakify/tools/clsx";
import { useIsPasswordRevealed } from "keycloakify/tools/useIsPasswordRevealed";
import { getKcClsx, type KcClsx } from "keycloakify/login/lib/kcClsx";
import type { PageProps } from "keycloakify/login/pages/PageProps";
import type { KcContext } from "../KcContext";
import type { I18n } from "../i18n";

export default function LoginPassword(props: PageProps<Extract<KcContext, { pageId: "login-password.ftl" }>, I18n>) {
  const { kcContext, i18n, doUseDefaultCss, Template, classes } = props;

  const { kcClsx } = getKcClsx({
    doUseDefaultCss,
    classes
  });

  const { realm, url, messagesPerField } = kcContext;

  const { msg, msgStr } = i18n;

  const [isLoginButtonDisabled, setIsLoginButtonDisabled] = useState(false);

  return (
    <Template
      kcContext={kcContext}
      i18n={i18n}
      doUseDefaultCss={doUseDefaultCss}
      classes={classes}
      headerNode={msg("doLogIn")}
      displayMessage={!messagesPerField.existsError("password")}
    >
      <div id="kc-form">
        <div id="kc-form-wrapper">
          <form
            id="kc-form-login"
            onSubmit={() => {
              setIsLoginButtonDisabled(true);
              return true;
            }}
            action={url.loginAction}
            method="post"
          >
            <div className={clsx(kcClsx("kcFormGroupClass"), "no-bottom-margin")}>
              <hr />
              <label htmlFor="password" className={kcClsx("kcLabelClass")}>
                {msg("password")}
              </label>

              <PasswordWrapper kcClsx={kcClsx} i18n={i18n} passwordInputId="password">
                <input
                  tabIndex={2}
                  id="password"
                  className={kcClsx("kcInputClass")}
                  name="password"
                  type="password"
                  autoFocus
                  autoComplete="on"
                  aria-invalid={messagesPerField.existsError("username", "password")}
                />
              </PasswordWrapper>

              {messagesPerField.existsError("password") && (
                <span
                  id="input-error-password"
                  className={kcClsx("kcInputErrorMessageClass")}
                  aria-live="polite"
                  dangerouslySetInnerHTML={{
                    __html: kcSanitize(messagesPerField.get("password"))
                  }}
                />
              )}
            </div>
            <div className={kcClsx("kcFormGroupClass", "kcFormSettingClass")}>
              <div id="kc-form-options" />
              <div className={kcClsx("kcFormOptionsWrapperClass")}>
                {realm.resetPasswordAllowed && (
                  <span>
                    <a tabIndex={5} href={url.loginResetCredentialsUrl}>
                      {msg("doForgotPassword")}
                    </a>
                  </span>
                )}
              </div>
            </div>
            <div id="kc-form-buttons" className={kcClsx("kcFormGroupClass")}>
              <input
                tabIndex={4}
                className={kcClsx("kcButtonClass", "kcButtonPrimaryClass", "kcButtonBlockClass", "kcButtonLargeClass")}
                name="login"
                id="kc-login"
                type="submit"
                value={msgStr("doLogIn")}
                disabled={isLoginButtonDisabled}
              />
            </div>
          </form>
        </div>
      </div>
    </Template>
  );
}

function PasswordWrapper(props: { kcClsx: KcClsx; i18n: I18n; passwordInputId: string; children: JSX.Element }) {
  const { kcClsx, i18n, passwordInputId, children } = props;

  const { msgStr } = i18n;

  const { isPasswordRevealed, toggleIsPasswordRevealed } = useIsPasswordRevealed({ passwordInputId });

  return (
    <div className={kcClsx("kcInputGroup")}>
      {children}
      <button
        type="button"
        className={kcClsx("kcFormPasswordVisibilityButtonClass")}
        aria-label={msgStr(isPasswordRevealed ? "hidePassword" : "showPassword")}
        aria-controls={passwordInputId}
        onClick={toggleIsPasswordRevealed}
      >
        <i className={kcClsx(isPasswordRevealed ? "kcFormPasswordVisibilityIconHide" : "kcFormPasswordVisibilityIconShow")} aria-hidden />
      </button>
    </div>
  );
}
