// src/login/pages/LoginPageExpired.tsx
import type { PageProps } from "keycloakify/login/pages/PageProps";
import type { KcContext } from "../KcContext";
import type { I18n } from "../i18n";

export default function LoginPageExpired(props: PageProps<Extract<KcContext, { pageId: "login-page-expired.ftl" }>, I18n>) {
  const { kcContext, i18n, doUseDefaultCss, Template, classes } = props;

  const { url } = kcContext;

  const { msg } = i18n;

  return (
    <Template kcContext={kcContext} i18n={i18n} doUseDefaultCss={doUseDefaultCss} classes={classes} headerNode={msg("pageExpiredTitle")}>
      <p id="instruction1" className="instruction">
        {msg("pageExpiredMsg1")}
        <a id="loginRestartLink" href={url.loginRestartFlowUrl}>
          {msg("doClickHere")}{" "}
        </a>{" "}
        .<br />
        {msg("pageExpiredMsg2")}{" "}
        <a id="loginContinueLink" href={url.loginAction}>
          {msg("doClickHere")}
        </a>{" "}
        .
      </p>
    </Template>
  );
}

// src/login/pages/LoginPageExpired.svelte
<script lang="ts">
  import type { PageProps } from "@keycloakify/svelte/login/pages/PageProps";
  import type { KcContext } from "../KcContext";
  import type { I18n } from "../i18n";

  const {
    Template,
    kcContext,
    i18n,
    doUseDefaultCss,
    classes,
  }: PageProps<
    Extract<KcContext, { pageId: "login-page-expired.ftl" }>,
    I18n
  > = $props();

  const { url } = kcContext;

  const { msg } = $i18n;
</script>

<Template {kcContext} {i18n} {doUseDefaultCss} {classes}>
  {#snippet headerNode()}
    {@render msg("pageExpiredTitle")()}
  {/snippet}

  <p id="instruction1" class="instruction">
    {@render msg("pageExpiredMsg1")()}
    <a id="loginRestartLink" href={url.loginRestartFlowUrl}>
      {@render msg("doClickHere")()}
    </a>
    {" "}
    .
    <br />
    {@render msg("pageExpiredMsg2")()}{" "}
    <a id="loginContinueLink" href={url.loginAction}>
      {@render msg("doClickHere")()}
    </a>
    {" "}
    .
  </p>
</Template>
