// src/login/pages/Login.tsx
import type { JSX } from "keycloakify/tools/JSX";
import { useState } from "react";
import { kcSanitize } from "keycloakify/lib/kcSanitize";
import { useIsPasswordRevealed } from "keycloakify/tools/useIsPasswordRevealed";
import { clsx } from "keycloakify/tools/clsx";
import type { PageProps } from "keycloakify/login/pages/PageProps";
import { getKcClsx, type KcClsx } from "keycloakify/login/lib/kcClsx";
import type { KcContext } from "../KcContext";
import type { I18n } from "../i18n";

export default function Login(props: PageProps<Extract<KcContext, { pageId: "login.ftl" }>, I18n>) {
  const { kcContext, i18n, doUseDefaultCss, Template, classes } = props;

  const { kcClsx } = getKcClsx({
    doUseDefaultCss,
    classes
  });

  const { social, realm, url, usernameHidden, login, auth, registrationDisabled, messagesPerField } = kcContext;

  const { msg, msgStr } = i18n;

  const [isLoginButtonDisabled, setIsLoginButtonDisabled] = useState(false);

  return (
    <Template
      kcContext={kcContext}
      i18n={i18n}
      doUseDefaultCss={doUseDefaultCss}
      classes={classes}
      displayMessage={!messagesPerField.existsError("username", "password")}
      headerNode={msg("loginAccountTitle")}
      displayInfo={realm.password && realm.registrationAllowed && !registrationDisabled}
      infoNode={
        <div id="kc-registration-container">
          <div id="kc-registration">
            <span>
              {msg("noAccount")}{" "}
              <a tabIndex={8} href={url.registrationUrl}>
                {msg("doRegister")}
              </a>
            </span>
          </div>
        </div>
      }
      socialProvidersNode={
        <>
          {realm.password && social?.providers !== undefined && social.providers.length !== 0 && (
            <div id="kc-social-providers" className={kcClsx("kcFormSocialAccountSectionClass")}>
              <hr />
              <h2>{msg("identity-provider-login-label")}</h2>
              <ul className={kcClsx("kcFormSocialAccountListClass", social.providers.length > 3 && "kcFormSocialAccountListGridClass")}>
                {social.providers.map((...[p, , providers]) => (
                  <li key={p.alias}>
                    <a
                      id={`social-${p.alias}`}
                      className={kcClsx("kcFormSocialAccountListButtonClass", providers.length > 3 && "kcFormSocialAccountGridItem")}
                      type="button"
                      href={p.loginUrl}
                    >
                      {p.iconClasses && <i className={clsx(kcClsx("kcCommonLogoIdP"), p.iconClasses)} aria-hidden="true"></i>}
                      <span
                        className={clsx(kcClsx("kcFormSocialAccountNameClass"), p.iconClasses && "kc-social-icon-text")}
                        dangerouslySetInnerHTML={{ __html: kcSanitize(p.displayName) }}
                      ></span>
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </>
      }
    >
      <div id="kc-form">
        <div id="kc-form-wrapper">
          {realm.password && (
            <form
              id="kc-form-login"
              onSubmit={() => {
                setIsLoginButtonDisabled(true);
                return true;
              }}
              action={url.loginAction}
              method="post"
            >
              {!usernameHidden && (
                <div className={kcClsx("kcFormGroupClass")}>
                  <label htmlFor="username" className={kcClsx("kcLabelClass")}>
                    {!realm.loginWithEmailAllowed ? msg("username") : !realm.registrationEmailAsUsername ? msg("usernameOrEmail") : msg("email")}
                  </label>
                  <input
                    tabIndex={2}
                    id="username"
                    className={kcClsx("kcInputClass")}
                    name="username"
                    defaultValue={login.username ?? ""}
                    type="text"
                    autoFocus
                    autoComplete="username"
                    aria-invalid={messagesPerField.existsError("username", "password")}
                  />
                  {messagesPerField.existsError("username", "password") && (
                    <span
                      id="input-error"
                      className={kcClsx("kcInputErrorMessageClass")}
                      aria-live="polite"
                      dangerouslySetInnerHTML={{
                        __html: kcSanitize(messagesPerField.getFirstError("username", "password"))
                      }}
                    />
                  )}
                </div>
              )}

              <div className={kcClsx("kcFormGroupClass")}>
                <label htmlFor="password" className={kcClsx("kcLabelClass")}>
                  {msg("password")}
                </label>
                <PasswordWrapper kcClsx={kcClsx} i18n={i18n} passwordInputId="password">
                  <input
                    tabIndex={3}
                    id="password"
                    className={kcClsx("kcInputClass")}
                    name="password"
                    type="password"
                    autoComplete="current-password"
                    aria-invalid={messagesPerField.existsError("username", "password")}
                  />
                </PasswordWrapper>
                {usernameHidden && messagesPerField.existsError("username", "password") && (
                  <span
                    id="input-error"
                    className={kcClsx("kcInputErrorMessageClass")}
                    aria-live="polite"
                    dangerouslySetInnerHTML={{
                      __html: kcSanitize(messagesPerField.getFirstError("username", "password"))
                    }}
                  />
                )}
              </div>

              <div className={kcClsx("kcFormGroupClass", "kcFormSettingClass")}>
                <div id="kc-form-options">
                  {realm.rememberMe && !usernameHidden && (
                    <div className="checkbox">
                      <label>
                        <input tabIndex={5} id="rememberMe" name="rememberMe" type="checkbox" defaultChecked={!!login.rememberMe} />{" "}
                        {msg("rememberMe")}
                      </label>
                    </div>
                  )}
                </div>
                <div className={kcClsx("kcFormOptionsWrapperClass")}>
                  {realm.resetPasswordAllowed && (
                    <span>
                      <a tabIndex={6} href={url.loginResetCredentialsUrl}>
                        {msg("doForgotPassword")}
                      </a>
                    </span>
                  )}
                </div>
              </div>

              <div id="kc-form-buttons" className={kcClsx("kcFormGroupClass")}>
                <input type="hidden" id="id-hidden-input" name="credentialId" value={auth.selectedCredential} />
                <input
                  tabIndex={7}
                  disabled={isLoginButtonDisabled}
                  className={kcClsx("kcButtonClass", "kcButtonPrimaryClass", "kcButtonBlockClass", "kcButtonLargeClass")}
                  name="login"
                  id="kc-login"
                  type="submit"
                  value={msgStr("doLogIn")}
                />
              </div>
            </form>
          )}
        </div>
      </div>
    </Template>
  );
}

function PasswordWrapper(props: { kcClsx: KcClsx; i18n: I18n; passwordInputId: string; children: JSX.Element }) {
  const { kcClsx, i18n, passwordInputId, children } = props;

  const { msgStr } = i18n;

  const { isPasswordRevealed, toggleIsPasswordRevealed } = useIsPasswordRevealed({ passwordInputId });

  return (
    <div className={kcClsx("kcInputGroup")}>
      {children}
      <button
        type="button"
        className={kcClsx("kcFormPasswordVisibilityButtonClass")}
        aria-label={msgStr(isPasswordRevealed ? "hidePassword" : "showPassword")}
        aria-controls={passwordInputId}
        onClick={toggleIsPasswordRevealed}
      >
        <i className={kcClsx(isPasswordRevealed ? "kcFormPasswordVisibilityIconHide" : "kcFormPasswordVisibilityIconShow")} aria-hidden />
      </button>
    </div>
  );
}

// src/login/pages/Login.svelte
<script lang="ts">
  import PasswordWrapper from "@keycloakify/svelte/login/components/PasswordWrapper.svelte";
  import type { PageProps } from "@keycloakify/svelte/login/pages/PageProps";
  import { useState } from "@keycloakify/svelte/tools/useState";
  import { kcSanitize } from "keycloakify/lib/kcSanitize";
  import { getKcClsx } from "keycloakify/login/lib/kcClsx";
  import { clsx } from "keycloakify/tools/clsx";
  import type { I18n } from "../i18n";
  import type { KcContext } from "../KcContext";
  const {
    kcContext,
    i18n,
    doUseDefaultCss,
    Template,
    classes,
  }: PageProps<Extract<KcContext, { pageId: "login.ftl" }>, I18n> = $props();
  const { kcClsx } = getKcClsx({
    doUseDefaultCss,
    classes,
  });

  const {
    social,
    realm,
    url,
    usernameHidden,
    login,
    auth,
    registrationDisabled,
    messagesPerField,
  } = kcContext;

  const { msg, msgStr } = $i18n;

  const [isLoginButtonDisabled, setIsLoginButtonDisabled] = useState(false);
</script>

<Template
  {kcContext}
  {i18n}
  {doUseDefaultCss}
  {classes}
  displayMessage={!messagesPerField.existsError("username", "password")}
  displayInfo={realm.password &&
    realm.registrationAllowed &&
    !registrationDisabled}
>
  {#snippet headerNode()}
    {@render msg("loginAccountTitle")()}
  {/snippet}

  {#snippet infoNode()}
    <div id="kc-registration-container">
      <div id="kc-registration">
        <span>
          {@render msg("noAccount")()}{" "}
          <a tabindex={8} href={url.registrationUrl}>
            {@render msg("doRegister")()}
          </a>
        </span>
      </div>
    </div>
  {/snippet}
  {#snippet socialProvidersNode()}
    {@const providers = social?.providers}
    {#if realm.password && !!providers && !!providers.length}
      <div
        id="kc-social-providers"
        class={kcClsx("kcFormSocialAccountSectionClass")}
      >
        <hr />
        <h2>{@render msg("identity-provider-login-label")()}</h2>
        <ul
          class={kcClsx(
            "kcFormSocialAccountListClass",
            providers.length > 3 && "kcFormSocialAccountListGridClass",
          )}
        >
          {#each providers as p}
            <li>
              <a
                id={`social-${p.alias}`}
                class={kcClsx(
                  "kcFormSocialAccountListButtonClass",
                  providers.length > 3 && "kcFormSocialAccountGridItem",
                )}
                type="button"
                href={p.loginUrl}
              >
                {#if p.iconClasses}
                  <i
                    class={clsx(kcClsx("kcCommonLogoIdP"), p.iconClasses)}
                    aria-hidden="true"
                  ></i>
                {/if}
                <span
                  class={clsx(
                    kcClsx("kcFormSocialAccountNameClass"),
                    p.iconClasses && "kc-social-icon-text",
                  )}
                >
                  {@html kcSanitize(p.displayName)}
                </span>
              </a>
            </li>
          {/each}
        </ul>
      </div>
    {/if}
  {/snippet}
  <div id="kc-form">
    <div id="kc-form-wrapper">
      {#if realm.password}
        <form
          id="kc-form-login"
          onsubmit={() => {
            setIsLoginButtonDisabled(true);
            return true;
          }}
          action={url.loginAction}
          method="post"
        >
          {#if !usernameHidden}
            <div class={kcClsx("kcFormGroupClass")}>
              <label for="username" class={kcClsx("kcLabelClass")}>
                {@render (!realm.loginWithEmailAllowed
                  ? msg("username")
                  : !realm.registrationEmailAsUsername
                    ? msg("usernameOrEmail")
                    : msg("email"))()}
              </label>
              <!-- svelte-ignore a11y_autofocus -->
              <input
                tabindex={2}
                id="username"
                class={kcClsx("kcInputClass")}
                name="username"
                value={login.username ?? ""}
                type="text"
                autofocus
                autocomplete="username"
                aria-invalid={messagesPerField.existsError(
                  "username",
                  "password",
                )}
              />
              {#if messagesPerField.existsError("username", "password")}
                <span
                  id="input-error"
                  class={kcClsx("kcInputErrorMessageClass")}
                  aria-live="polite"
                >
                  {@html kcSanitize(
                    messagesPerField.getFirstError("username", "password"),
                  )}
                </span>
              {/if}
            </div>
          {/if}

          <div class={kcClsx("kcFormGroupClass")}>
            <label for="password" class={kcClsx("kcLabelClass")}>
              {@render msg("password")()}
            </label>
            <PasswordWrapper {kcClsx} {i18n} passwordInputId="password">
              <input
                tabindex={3}
                id="password"
                class={kcClsx("kcInputClass")}
                name="password"
                type="password"
                autocomplete="current-password"
                aria-invalid={messagesPerField.existsError(
                  "username",
                  "password",
                )}
              />
            </PasswordWrapper>
            {#if usernameHidden && messagesPerField.existsError("username", "password")}
              <span
                id="input-error"
                class={kcClsx("kcInputErrorMessageClass")}
                aria-live="polite"
              >
                {@html kcSanitize(
                  messagesPerField.getFirstError("username", "password"),
                )}
              </span>
            {/if}
          </div>

          <div class={kcClsx("kcFormGroupClass", "kcFormSettingClass")}>
            <div id="kc-form-options">
              {#if realm.rememberMe && !usernameHidden}
                <div class="checkbox">
                  <label>
                    <input
                      tabindex={5}
                      id="rememberMe"
                      name="rememberMe"
                      type="checkbox"
                      checked={!!login.rememberMe}
                    />
                    {" "}
                    {@render msg("rememberMe")()}
                  </label>
                </div>
              {/if}
            </div>
            <div class={kcClsx("kcFormOptionsWrapperClass")}>
              {#if realm.resetPasswordAllowed}
                <span>
                  <a tabindex={6} href={url.loginResetCredentialsUrl}>
                    {@render msg("doForgotPassword")()}
                  </a>
                </span>
              {/if}
            </div>
          </div>

          <div id="kc-form-buttons" class={kcClsx("kcFormGroupClass")}>
            <input
              type="hidden"
              id="id-hidden-input"
              name="credentialId"
              value={auth.selectedCredential}
            />
            <input
              tabindex={7}
              disabled={$isLoginButtonDisabled}
              class={kcClsx(
                "kcButtonClass",
                "kcButtonPrimaryClass",
                "kcButtonBlockClass",
                "kcButtonLargeClass",
              )}
              name="login"
              id="kc-login"
              type="submit"
              value={msgStr("doLogIn")}
            />
          </div>
        </form>
      {/if}
    </div>
  </div>
</Template>
