// src/login/pages/Register.svelte
<script lang="ts">
  import type { UserProfileFormFieldsProps } from "@keycloakify/svelte/login/components/UserProfileFormFieldsProps";
  import type { PageProps } from "@keycloakify/svelte/login/pages/PageProps";
  import { useState } from "@keycloakify/svelte/tools/useState";
  import { getKcClsx } from "keycloakify/login/lib/kcClsx";
  import { clsx } from "keycloakify/tools/clsx";
  import type { Component } from "svelte";
  import TermsAcceptance from "../components/TermsAcceptance.svelte";
  import type { I18n } from "../i18n";
  import type { KcContext } from "../KcContext";

  type RegisterProps = PageProps<
    Extract<KcContext, { pageId: "register.ftl" }>,
    I18n
  > & {
    UserProfileFormFields: Component<UserProfileFormFieldsProps>;
    doMakeUserConfirmPassword: boolean;
  };
  const props: RegisterProps = $props();
  const {
    kcContext,
    i18n,
    doUseDefaultCss,
    Template,
    classes,
    UserProfileFormFields,
    doMakeUserConfirmPassword,
  } = props;
  const { kcClsx } = getKcClsx({
    doUseDefaultCss,
    classes,
  });

  const {
    messageHeader,
    url,
    messagesPerField,
    recaptchaRequired,
    recaptchaVisible,
    recaptchaSiteKey,
    recaptchaAction,
    termsAcceptanceRequired,
  } = kcContext;

  const { msg, msgStr, advancedMsg } = $i18n;

  const [isFormSubmittable, setIsFormSubmittable] = useState(false);
  const [areTermsAccepted, setAreTermsAccepted] = useState(false);
</script>

<Template
  {kcContext}
  {i18n}
  {doUseDefaultCss}
  {classes}
  displayMessage={messagesPerField.exists("global")}
  displayRequiredFields={true}
>
  {#snippet headerNode()}
    {#if messageHeader !== undefined}
      {@render advancedMsg(messageHeader)()}
    {:else}
      {@render msg("registerTitle")()}
    {/if}
  {/snippet}
  <form
    id="kc-register-form"
    class={kcClsx("kcFormClass")}
    action={url.registrationAction}
    method="post"
  >
    <UserProfileFormFields
      {kcContext}
      {i18n}
      {kcClsx}
      onIsFormSubmittableValueChange={setIsFormSubmittable}
      {doMakeUserConfirmPassword}
    />
    {#if termsAcceptanceRequired}
      <TermsAcceptance
        {i18n}
        {kcClsx}
        {messagesPerField}
        areTermsAccepted={$areTermsAccepted}
        onAreTermsAcceptedValueChange={setAreTermsAccepted}
      />
    {/if}
    {#if recaptchaRequired && (recaptchaVisible || recaptchaAction === undefined)}
      <div class="form-group">
        <div class={kcClsx("kcInputWrapperClass")}>
          <div
            class="g-recaptcha"
            data-size="compact"
            data-sitekey={recaptchaSiteKey}
            data-action={recaptchaAction}
          ></div>
        </div>
      </div>
    {/if}
    <div class={kcClsx("kcFormGroupClass")}>
      <div id="kc-form-options" class={kcClsx("kcFormOptionsClass")}>
        <div class={kcClsx("kcFormOptionsWrapperClass")}>
          <span>
            <a href={url.loginUrl}>{@render msg("backToLogin")()}</a>
          </span>
        </div>
      </div>
      {#if recaptchaRequired && !recaptchaVisible && recaptchaAction !== undefined}
        <div id="kc-form-buttons" class={kcClsx("kcFormButtonsClass")}>
          <button
            class={clsx(
              kcClsx(
                "kcButtonClass",
                "kcButtonPrimaryClass",
                "kcButtonBlockClass",
                "kcButtonLargeClass",
              ),
              "g-recaptcha",
            )}
            data-sitekey={recaptchaSiteKey}
            data-callback={() => {
              (
                document.getElementById("kc-register-form") as HTMLFormElement
              ).requestSubmit();
            }}
            data-action={recaptchaAction}
            type="submit"
          >
            {@render msg("doRegister")()}
          </button>
        </div>
      {:else}
        <div id="kc-form-buttons" class={kcClsx("kcFormButtonsClass")}>
          <input
            disabled={!$isFormSubmittable ||
              (termsAcceptanceRequired && !$areTermsAccepted)}
            class={kcClsx(
              "kcButtonClass",
              "kcButtonPrimaryClass",
              "kcButtonBlockClass",
              "kcButtonLargeClass",
            )}
            type="submit"
            value={msgStr("doRegister")}
          />
        </div>
      {/if}
    </div>
  </form>
</Template>

// src/login/pages/Register.tsx
import type { JSX } from "keycloakify/tools/JSX";
import { useState, useLayoutEffect } from "react";
import type { LazyOrNot } from "keycloakify/tools/LazyOrNot";
import { kcSanitize } from "keycloakify/lib/kcSanitize";
import { getKcClsx, type KcClsx } from "keycloakify/login/lib/kcClsx";
import { clsx } from "keycloakify/tools/clsx";
import type { UserProfileFormFieldsProps } from "keycloakify/login/UserProfileFormFieldsProps";
import type { PageProps } from "keycloakify/login/pages/PageProps";
import type { KcContext } from "../KcContext";
import type { I18n } from "../i18n";

type RegisterProps = PageProps<Extract<KcContext, { pageId: "register.ftl" }>, I18n> & {
  UserProfileFormFields: LazyOrNot<(props: UserProfileFormFieldsProps) => JSX.Element>;
  doMakeUserConfirmPassword: boolean;
};

export default function Register(props: RegisterProps) {
  const { kcContext, i18n, doUseDefaultCss, Template, classes, UserProfileFormFields, doMakeUserConfirmPassword } = props;

  const { kcClsx } = getKcClsx({
    doUseDefaultCss,
    classes
  });

  const { messageHeader, url, messagesPerField, recaptchaRequired, recaptchaVisible, recaptchaSiteKey, recaptchaAction, termsAcceptanceRequired } =
    kcContext;

  const { msg, msgStr, advancedMsg } = i18n;

  const [isFormSubmittable, setIsFormSubmittable] = useState(false);
  const [areTermsAccepted, setAreTermsAccepted] = useState(false);

  useLayoutEffect(() => {
    (window as any)["onSubmitRecaptcha"] = () => {
      // @ts-expect-error
      document.getElementById("kc-register-form").requestSubmit();
    };

    return () => {
      delete (window as any)["onSubmitRecaptcha"];
    };
  }, []);

  return (
    <Template
      kcContext={kcContext}
      i18n={i18n}
      doUseDefaultCss={doUseDefaultCss}
      classes={classes}
      headerNode={messageHeader !== undefined ? advancedMsg(messageHeader) : msg("registerTitle")}
      displayMessage={messagesPerField.exists("global")}
      displayRequiredFields
    >
      <form id="kc-register-form" className={kcClsx("kcFormClass")} action={url.registrationAction} method="post">
        <UserProfileFormFields
          kcContext={kcContext}
          i18n={i18n}
          kcClsx={kcClsx}
          onIsFormSubmittableValueChange={setIsFormSubmittable}
          doMakeUserConfirmPassword={doMakeUserConfirmPassword}
        />
        {termsAcceptanceRequired && (
          <TermsAcceptance
            i18n={i18n}
            kcClsx={kcClsx}
            messagesPerField={messagesPerField}
            areTermsAccepted={areTermsAccepted}
            onAreTermsAcceptedValueChange={setAreTermsAccepted}
          />
        )}
        {recaptchaRequired && (recaptchaVisible || recaptchaAction === undefined) && (
          <div className="form-group">
            <div className={kcClsx("kcInputWrapperClass")}>
              <div className="g-recaptcha" data-size="compact" data-sitekey={recaptchaSiteKey} data-action={recaptchaAction}></div>
            </div>
          </div>
        )}
        <div className={kcClsx("kcFormGroupClass")}>
          <div id="kc-form-options" className={kcClsx("kcFormOptionsClass")}>
            <div className={kcClsx("kcFormOptionsWrapperClass")}>
              <span>
                <a href={url.loginUrl}>{msg("backToLogin")}</a>
              </span>
            </div>
          </div>

          {recaptchaRequired && !recaptchaVisible && recaptchaAction !== undefined ? (
            <div id="kc-form-buttons" className={kcClsx("kcFormButtonsClass")}>
              <button
                className={clsx(kcClsx("kcButtonClass", "kcButtonPrimaryClass", "kcButtonBlockClass", "kcButtonLargeClass"), "g-recaptcha")}
                data-sitekey={recaptchaSiteKey}
                data-callback="onSubmitRecaptcha"
                data-action={recaptchaAction}
                type="submit"
              >
                {msg("doRegister")}
              </button>
            </div>
          ) : (
            <div id="kc-form-buttons" className={kcClsx("kcFormButtonsClass")}>
              <input
                disabled={!isFormSubmittable || (termsAcceptanceRequired && !areTermsAccepted)}
                className={kcClsx("kcButtonClass", "kcButtonPrimaryClass", "kcButtonBlockClass", "kcButtonLargeClass")}
                type="submit"
                value={msgStr("doRegister")}
              />
            </div>
          )}
        </div>
      </form>
    </Template>
  );
}

function TermsAcceptance(props: {
  i18n: I18n;
  kcClsx: KcClsx;
  messagesPerField: Pick<KcContext["messagesPerField"], "existsError" | "get">;
  areTermsAccepted: boolean;
  onAreTermsAcceptedValueChange: (areTermsAccepted: boolean) => void;
}) {
  const { i18n, kcClsx, messagesPerField, areTermsAccepted, onAreTermsAcceptedValueChange } = props;

  const { msg } = i18n;

  return (
    <>
      <div className="form-group">
        <div className={kcClsx("kcInputWrapperClass")}>
          {msg("termsTitle")}
          <div id="kc-registration-terms-text">{msg("termsText")}</div>
        </div>
      </div>
      <div className="form-group">
        <div className={kcClsx("kcLabelWrapperClass")}>
          <input
            type="checkbox"
            id="termsAccepted"
            name="termsAccepted"
            className={kcClsx("kcCheckboxInputClass")}
            checked={areTermsAccepted}
            onChange={e => onAreTermsAcceptedValueChange(e.target.checked)}
            aria-invalid={messagesPerField.existsError("termsAccepted")}
          />
          <label htmlFor="termsAccepted" className={kcClsx("kcLabelClass")}>
            {msg("acceptTerms")}
          </label>
        </div>
        {messagesPerField.existsError("termsAccepted") && (
          <div className={kcClsx("kcLabelWrapperClass")}>
            <span
              id="input-error-terms-accepted"
              className={kcClsx("kcInputErrorMessageClass")}
              aria-live="polite"
              dangerouslySetInnerHTML={{
                __html: kcSanitize(messagesPerField.get("termsAccepted"))
              }}
            />
          </div>
        )}
      </div>
    </>
  );
}
