// src/login/pages/UpdateEmail.svelte
<script lang="ts">
  import LogoutOtherSessions from "@keycloakify/svelte/login/components/LogoutOtherSessions.svelte";
  import type { UserProfileFormFieldsProps } from "@keycloakify/svelte/login/components/UserProfileFormFieldsProps";
  import type { PageProps } from "@keycloakify/svelte/login/pages/PageProps";
  import { useState } from "@keycloakify/svelte/tools/useState";
  import { getKcClsx } from "keycloakify/login/lib/kcClsx";
  import type { Component } from "svelte";
  import type { I18n } from "../i18n";
  import type { KcContext } from "../KcContext";

  type UpdateEmailProps = PageProps<
    Extract<KcContext, { pageId: "update-email.ftl" }>,
    I18n
  > & {
    UserProfileFormFields: Component<UserProfileFormFieldsProps>;
    doMakeUserConfirmPassword: boolean;
  };

  const {
    Template,
    kcContext,
    i18n,
    doUseDefaultCss,
    classes,
    UserProfileFormFields,
    doMakeUserConfirmPassword,
  }: UpdateEmailProps = $props();

  const { kcClsx } = getKcClsx({
    doUseDefaultCss,
    classes,
  });

  const { msg, msgStr } = $i18n;

  const [isFormSubmittable, setIsFormSubmittable] = useState(false);

  const { url, messagesPerField, isAppInitiatedAction } = kcContext;
</script>

<Template
  {kcContext}
  {i18n}
  {doUseDefaultCss}
  {classes}
  displayMessage={messagesPerField.exists("global")}
  displayRequiredFields={true}
>
  {#snippet headerNode()}
    {@render msg("updateEmailTitle")()}
  {/snippet}
  <form
    id="kc-update-email-form"
    class={kcClsx("kcFormClass")}
    action={url.loginAction}
    method="post"
  >
    <UserProfileFormFields
      {kcContext}
      {i18n}
      {kcClsx}
      onIsFormSubmittableValueChange={setIsFormSubmittable}
      {doMakeUserConfirmPassword}
    />

    <div class={kcClsx("kcFormGroupClass")}>
      <div id="kc-form-options" class={kcClsx("kcFormOptionsClass")}>
        <div class={kcClsx("kcFormOptionsWrapperClass")}></div>
      </div>

      <LogoutOtherSessions {kcClsx} {i18n} />

      <div id="kc-form-buttons" class={kcClsx("kcFormButtonsClass")}>
        <input
          disabled={!$isFormSubmittable}
          class={kcClsx(
            "kcButtonClass",
            "kcButtonPrimaryClass",
            "kcButtonBlockClass",
            "kcButtonLargeClass",
          )}
          type="submit"
          value={msgStr("doSubmit")}
        />
        {#if isAppInitiatedAction}
          <button
            class={kcClsx(
              "kcButtonClass",
              "kcButtonDefaultClass",
              "kcButtonLargeClass",
              "kcButtonBlockClass",
            )}
            type="submit"
            name="cancel-aia"
            value="true"
          >
            {@render msg("doCancel")()}
          </button>
        {/if}
      </div>
    </div>
  </form>
</Template>

// src/login/pages/UpdateEmail.tsx
import type { JSX } from "keycloakify/tools/JSX";
import { useState } from "react";
import type { LazyOrNot } from "keycloakify/tools/LazyOrNot";
import { getKcClsx, type KcClsx } from "keycloakify/login/lib/kcClsx";
import type { UserProfileFormFieldsProps } from "keycloakify/login/UserProfileFormFieldsProps";
import type { PageProps } from "keycloakify/login/pages/PageProps";
import type { KcContext } from "../KcContext";
import type { I18n } from "../i18n";

type UpdateEmailProps = PageProps<Extract<KcContext, { pageId: "update-email.ftl" }>, I18n> & {
  UserProfileFormFields: LazyOrNot<(props: UserProfileFormFieldsProps) => JSX.Element>;
  doMakeUserConfirmPassword: boolean;
};

export default function UpdateEmail(props: UpdateEmailProps) {
  const { kcContext, i18n, doUseDefaultCss, Template, classes, UserProfileFormFields, doMakeUserConfirmPassword } = props;

  const { kcClsx } = getKcClsx({
    doUseDefaultCss,
    classes
  });

  const { msg, msgStr } = i18n;

  const [isFormSubmittable, setIsFormSubmittable] = useState(false);

  const { url, messagesPerField, isAppInitiatedAction } = kcContext;

  return (
    <Template
      kcContext={kcContext}
      i18n={i18n}
      doUseDefaultCss={doUseDefaultCss}
      classes={classes}
      displayMessage={messagesPerField.exists("global")}
      displayRequiredFields
      headerNode={msg("updateEmailTitle")}
    >
      <form id="kc-update-email-form" className={kcClsx("kcFormClass")} action={url.loginAction} method="post">
        <UserProfileFormFields
          kcContext={kcContext}
          i18n={i18n}
          kcClsx={kcClsx}
          onIsFormSubmittableValueChange={setIsFormSubmittable}
          doMakeUserConfirmPassword={doMakeUserConfirmPassword}
        />

        <div className={kcClsx("kcFormGroupClass")}>
          <div id="kc-form-options" className={kcClsx("kcFormOptionsClass")}>
            <div className={kcClsx("kcFormOptionsWrapperClass")} />
          </div>

          <LogoutOtherSessions kcClsx={kcClsx} i18n={i18n} />

          <div id="kc-form-buttons" className={kcClsx("kcFormButtonsClass")}>
            <input
              disabled={!isFormSubmittable}
              className={kcClsx("kcButtonClass", "kcButtonPrimaryClass", !isAppInitiatedAction && "kcButtonBlockClass", "kcButtonLargeClass")}
              type="submit"
              value={msgStr("doSubmit")}
            />
            {isAppInitiatedAction && (
              <button className={kcClsx("kcButtonClass", "kcButtonDefaultClass", "kcButtonLargeClass")} type="submit" name="cancel-aia" value="true">
                {msg("doCancel")}
              </button>
            )}
          </div>
        </div>
      </form>
    </Template>
  );
}

function LogoutOtherSessions(props: { kcClsx: KcClsx; i18n: I18n }) {
  const { kcClsx, i18n } = props;

  const { msg } = i18n;

  return (
    <div id="kc-form-options" className={kcClsx("kcFormOptionsClass")}>
      <div className={kcClsx("kcFormOptionsWrapperClass")}>
        <div className="checkbox">
          <label>
            <input type="checkbox" id="logout-sessions" name="logout-sessions" value="on" defaultChecked={true} />
            {msg("logoutOtherSessions")}
          </label>
        </div>
      </div>
    </div>
  );
}
